SELECT * FROM LIVRO JOIN LIVRO_CATEGORIA JOIN AUTOR JOIN LIVRO_AUTOR JOIN CATEGORIA;

SELECT  L.CD_LIVRO, L.CD_ISBN, L.NM_LIVRO, L.AA_EDICAO,
		L.DS_SINOPSE, GROUP_CONCAT(LA.CD_AUTOR)
FROM LIVRO L
	JOIN LIVRO_AUTOR LA
		ON(LA.CD_LIVRO = L.CD_LIVRO)
ORDER BY L.CD_LIVRO;