Delimiter $$
DROP PROCEDURE IF EXISTS LoadBooksNonFilter$$
CREATE PROCEDURE LoadBooksNonFilter()
BEGIN
	SELECT  L.CD_LIVRO, L.CD_ISBN, L.NM_LIVRO, L.AA_EDICAO,
			L.DS_SINOPSE, E.CD_EDITORA, E.NM_EDITORA,
			GROUP_CONCAT(DISTINCT A.CD_AUTOR) AS CD_AUTORES,
			GROUP_CONCAT(DISTINCT A.NM_AUTOR) AS NM_AUTORES, 
			GROUP_CONCAT(DISTINCT C.CD_CATEGORIA) AS CD_CATEGORIAS, 
			GROUP_CONCAT(DISTINCT C.NM_CATEGORIA) AS NM_CATEGORIAS
		FROM LIVRO L
		JOIN EDITORA E ON E.CD_EDITORA = L.CD_EDITORA
		LEFT JOIN LIVRO_CATEGORIA LC ON LC.CD_LIVRO = L.CD_LIVRO
		LEFT JOIN CATEGORIA C ON LC.CD_CATEGORIA = C.CD_CATEGORIA
		LEFT JOIN LIVRO_AUTOR LA ON LA.CD_LIVRO = L.CD_LIVRO
		LEFT JOIN AUTOR A ON LA.CD_AUTOR = A.CD_AUTOR
		GROUP BY L.CD_LIVRO;
END$$

DROP PROCEDURE IF EXISTS LoadBooksFilter$$
CREATE PROCEDURE LoadBooksFilter(vFiltro TEXT)
BEGIN
	SELECT  L.CD_LIVRO, L.CD_ISBN, L.NM_LIVRO, L.AA_EDICAO,
			L.DS_SINOPSE, E.CD_EDITORA, E.NM_EDITORA,
			GROUP_CONCAT(DISTINCT A.CD_AUTOR) AS CD_AUTORES,
			GROUP_CONCAT(DISTINCT A.NM_AUTOR) AS NM_AUTORES, 
			GROUP_CONCAT(DISTINCT C.CD_CATEGORIA) AS CD_CATEGORIAS, 
			GROUP_CONCAT(DISTINCT C.NM_CATEGORIA) AS NM_CATEGORIAS
		FROM LIVRO L
		JOIN EDITORA E ON E.CD_EDITORA = L.CD_EDITORA
		LEFT JOIN LIVRO_CATEGORIA LC ON LC.CD_LIVRO = L.CD_LIVRO
		LEFT JOIN CATEGORIA C ON LC.CD_CATEGORIA = C.CD_CATEGORIA
		LEFT JOIN LIVRO_AUTOR LA ON LA.CD_LIVRO = L.CD_LIVRO
		LEFT JOIN AUTOR A ON LA.CD_AUTOR = A.CD_AUTOR
		WHERE L.NM_LIVRO LIKE ('%' + vFiltro + '%') 
			OR A.NM_AUTOR LIKE ('%' + vFiltro + '%')
		GROUP BY L.CD_LIVRO;
END$$

Delimiter ;
